import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { getServerSession } from "next-auth";
import Providers from "../layout/provider";
import { LanguageProvider } from "../components/language-provider";
import "./globals.css";

import { Poppins, Fira_Code } from "next/font/google";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600"],
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-firacode",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${firaCode.variable} font-sans`}>
        <AppRouterCacheProvider>
          <LanguageProvider>
            <Providers session={session}>
              <main className="flex-1 overflow-auto p-4 bg-gray-50">
                {children}
              </main>
            </Providers>
          </LanguageProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
